version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      custom:
        ipv4_address: 172.28.1.1
  toxiproxy:
    image: shopify/toxiproxy
    container_name: proxy
    expose:
      - "6666"
      - "8474"
    ports:
      - "6666:6666"
      - "8474:8474"
    networks:
      custom:
        ipv4_address: 172.28.1.2
  app:
    build: .
    links:
      - redis
    depends_on:
      - redis
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=3000
    networks:
      custom:
        ipv4_address: 172.28.1.3
    command:
      sh -c 'node server.js'
networks:
  custom:
    driver: bridge
    internal: false
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/16
