version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
  toxiproxy:
    image: shopify/toxiproxy
    container_name: proxy
    expose:
      - 8474
      - 6666
    ports:
      - 6666:6666
      - 8474:8474
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
  app:
    build: ./
    volumes:
      - ./:/var/www/app
    links:
      - redis
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=3000
    networks:
      testing_net:
        ipv4_address: 172.28.1.3
    command:
      sh -c 'npm i && node server.js'
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
