version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Build service
          command: docker-compose build --pull

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d

      - run:
          name: Run tests
          command: |
            npm install
            node setup-proxy.js
            curl localhost:3000

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
